### ISSUE TITLE
What is `Clanc C -Ofast`

### ISSUE THREAD

**Issue by AsynchronousAI** [ExtReMLapin/fast_brainfuck.lua#7]
I saw it in the benchmarks and I have never heard of it.

**Comment by ExtReMLapin** [comment]
Sorry for slow answer, had a rough weekend...


See this branch : https://github.com/ExtReMLapin/fast_brainfuck.lua/tree/c-transpiler

It turns intermediate representation into C code instead of LuaJIT code 

```lua
local IRToCode = {
	[INC] = "(*p) += %i; ",
	[MOVE] = "p += %i; ",
	[LOOPSTART] = "while ((*p) != 0) { ",
	[END] = " } ",
	[PRINT] = "putchar(*p); ",
	[READ] = "*p=getchar(); ",
	[ASSIGNATION] = "(*p)=%i;  ",
	[MEMSET] = "memset(p+%i, %i, %i); ",
	--[UNROLLED_ASSIGNATION] = "data[i+%i] = data[i+%i] + (-(data[i]/%i))*%i ",
	[UNROLLED_ASSIGNATION] = "*(p+%i) = *(p+%i) + (-(*p/%i))*%i; ",
	[IFSTART] = "if ((*p) != 0) {  "
}
```

The thing is that the C code is optimized but it's even faster because the LLVM optimizes the code even more, this is why it beats everything, but it's not "fair" to actually use it and compare it to Lua/LuaJIT
